image: ubuntu:latest

stages:
  - publish

before_script:
  - sudo apt update
  - sudo apt install docker-ce docker-ce-cli containerd.io
  - docker info

publish:
  stage: publish
  when: manual
  script:
    - docker login -u $registry_login -p $registry_password $registry_url
    - . ./scripts/build.sh
    - . ./scripts/publish.sh
  tags:
    - shell
